### PR TITLE
Support options in mix gradient

### PR DESCRIPTION
**Pull request by Premwoik**
This PR refers to #3 and adds some basic commands to the gradient mix task.

### Paths
We can select the target we want to type-check the following ways:
- [x] The module
```elixir
mix gradient -- Gradient.Fmt
```
- [x] The .ex file
```elixir
mix gradient -- lib/gradient/fmt.ex
```
- [x] The .beam file
```elixir
mix gradient -- _build/dev/lib/gradient/ebin/Elixir.Gradient.Fmt.beam
```
- [x] The directory
```elixir
mix gradient -- lib/gradient/
```

### Supported commands:
- [x] `--no-compile` - do not compile even if needed
- [x]  `--no-ex-check` - do not perform checks specyfic for Elixir (from ElixirChecker module)
- [x]  `--no-gradualizer-check` - do not perform the Gradualizer checks
- [x]  `--no-specify` - do not specify missing lines in AST what can result in less precise error messages
- [x] `--no-deps` - do not import dependencies to the Gradualizer
- [x] `--code-path` -  provide a path to the .ex file containing code for analyzed .beam
- [x]  `--stop_on_first_error` - stop type checking at the first error
- [x]  `--infer` - infer type information from literals and other language constructs,
- [x]  `--verbose` - show what Gradualizer is doing
- [x]  `--no-fancy` - do not use fancy error messages
- [x]  `--fmt-location none` - do not display location for easier comparison
- [x]  `--fmt-location brief` - display location for machine processing
- [x] `--fmt-location verbose` - display location for human readers (default)
- [x] `--no-colors` - do not use colors in printed messages
- [x] `--expr-color ansicode` - set color for expressions (default: cyan)
- [x] `--type-color ansicode` - set color for types
- [x] `--underscore-color ansicode` - set color for the underscored invalid code part
  in the fancy messages

### Other
- [x] Provide tests for the options

### Possible extensions
- Support verbose in Gradient AST specifying module
- Support a quiet option.

### CODE REVIEW

**Comment by erszcz** [comment]
Good stuff!

Do we need the `.beam` files under `test/` checked into the repo? There's quite a lot of them already as far as I can tell 🤔

**Comment by Premwoik** [comment]
Should I try to remove these files from the repo and compile them before tests if not exist?

**Comment by erszcz** [comment]
> Should I try to remove these files from the repo and compile them before tests if not exist?

Yes, I think so, but let's have another PR for that. This is good the way it is :+1:

**Comment by Premwoik** [comment]
> > Should I try to remove these files from the repo and compile them before tests if not exist?
> 
> Yes, I think so, but let's have another PR for that. This is good the way it is 👍

@erszcz I implemented such change here https://github.com/esl/gradient/pull/62

**Review by erszcz — APPROVED** [review]

**Comment by erszcz** [comment]
Awesome! Both these PRs look good, please merge in the order you think is better / easier to manage. Great job, thanks!

**Pull request merged**
